CREATE DATABASE DB_LIVROS DEFAULT CHARACTER SET = 'utf8mb4';

USE DB_LIVROS;

CREATE TABLE IF NOT EXISTS Livros (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor VARCHAR(255) NOT NULL,
    descricao TEXT,
    inicio DATE,
    fim DATE,
    status ENUM('quero ler', 'lendo', 'lido') DEFAULT 'quero ler',
    createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);